name: Rust Docs

on:
  push:
    branches: [kiz-umbrella-crates]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Setup protoc
      - name: Set up Protocol Buffers
        uses: arduino/setup-protoc@v1

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rust-docs
          target: wasm32-unknown-unknown

      - name: Generate docs
        run: cargo doc -p developer-hub -p sp-io -p sp-runtime -p frame -p frame-support --no-deps

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: target/doc # The folder the action should deploy.
